sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123123
  alioss:
    endpoint: https://oss-cn-shanghai.aliyuncs.com
    access-key-id: LTAI5tETyCZy1Q5iXixiEu8E
    access-key-secret: uHHOet7rzAmo8qjokkAsR1lRlVfFv9
    bucket-name: ecust-web-jwq